name: Build KillrVideo Python FastAPI backend
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Poetry
      run: pip install poetry
    - name: Install pydantic
      run: pip install pydantic
    - name: Install google-api-python-client
      run: pip install google-api-python-client
    - name: Install grpcio-tools
      run: pip install grpcio-tools
    - name: Install grpc-tools
      run: pip install grpc-tools
    - name: Install astrapy
      run: pip install astrapy
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Run tests
      env: 
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: poetry run pytest
    - name: Run linting
      run: |
        poetry run ruff check .
        poetry run ruff format .
    - name: Run type checks
      run: poetry run mypy .
